# fly.toml app configuration file generated for counter-server on 2024-05-20T20:26:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'counter-server'
primary_region = 'nrt'

[build]

[env]
  PORT='3000'
  MONGO_CONNECTION_TEST_URL='mongodb://127.0.0.1:27017/counter_server_test'
  MONGO_CONNECTION_URL='mongodb+srv://jeffbukk00:MOKFLAe4i036i9nO@counter.1mebdj9.mongodb.net/counter?retryWrites=true&w=majority&appName=counter'
  CLIENT_HOST='https://www.counter.today'
  OAUTH_GOOGLE_CLIENT_ID='241159883621-rki5592haaf1bhmcqi5afjkah1ab3sd9.apps.googleusercontent.com'
  OAUTH_GOOGLE_REDIRECT_URL='https://www.counter.today/landing/auth/callback/google'
  OAUTH_NAVER_CLIENT_ID='sL8pJDTCAElM5Y2xomLK'
  OAUTH_NAVER_REDIRECT_URL='https://www.counter.today/landing/auth/callback/naver'
  OAUTH_KAKAO_CLIENT_ID='e5bc8f070efdb827aba5007583860ee8'
  OAUTH_KAKAO_REDIRECT_URL='https://www.counter.today/landing/auth/callback/kakao'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
